packages:
  - apps/*
  - packages/*
  - services/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - argon2
  - esbuild
  - prisma
  - protobufjs
