import { checkSyntax } from './expression';

/**
 * Workflow graph: Trigger -> AI Agent -> Tool -> Condition -> Action, as nodes and edges. The
 * validator is the single gate for every graph that is saved, generated by Build with AI or
 * loaded from a template. Node types are a registry (NODE_TYPES); adding one means adding its
 * data check here and its executor in runtime/nodes.ts.
 */

export interface GraphNode {
  id: string;
  type: string;
  position?: { x: number; y: number };
  data?: Record<string, unknown>;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string | null;
  label?: string | null;
}

export interface Graph {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface GraphIssue {
  path: string;
  message: string;
}

export const TRIGGER_SOURCES = ['api', 'webhook', 'schedule', 'manual'] as const;
export const ACTION_KINDS = ['send_email', 'notify', 'http_request', 'progrid'] as const;

const ID = /^[A-Za-z][A-Za-z0-9_-]{0,63}$/;
export const MAX_NODES = 100;
export const MAX_EDGES = 300;

const isObj = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);

/** Checks each node type's data. Returns issues (empty when fine). */
type DataCheck = (data: Record<string, unknown>, ctx: ValidateOptions) => string[];

export const NODE_TYPES: Record<string, DataCheck> = {
  trigger: (d) => {
    const out: string[] = [];
    const source = d.source ?? 'api';
    if (!TRIGGER_SOURCES.includes(source as never)) out.push(`source must be one of ${TRIGGER_SOURCES.join(', ')}`);
    if (source === 'schedule' && (typeof d.cron !== 'string' || !isCron(d.cron))) out.push('a schedule trigger needs cron, five fields like "0 9 * * 1-5"');
    return out;
  },
  agent: (d, ctx) => {
    const out: string[] = [];
    if (typeof d.prompt !== 'string' || !d.prompt.trim()) out.push('prompt is required');
    if (d.toolIds !== undefined) {
      if (!Array.isArray(d.toolIds) || d.toolIds.some((t) => typeof t !== 'string')) out.push('toolIds must be a list of tool ids');
      else if (ctx.toolIds) for (const t of d.toolIds as string[]) if (!ctx.toolIds.has(t)) out.push(`unknown tool ${t}`);
    }
    if (d.outputSchema !== undefined && d.outputSchema !== null && !isObj(d.outputSchema)) out.push('outputSchema must be a JSON Schema object');
    return out;
  },
  tool: (d, ctx) => {
    const out: string[] = [];
    if (typeof d.toolId !== 'string' || !d.toolId) out.push('toolId is required');
    else if (ctx.toolIds && !ctx.toolIds.has(d.toolId)) out.push(`unknown tool ${d.toolId}`);
    if (d.input !== undefined && !isObj(d.input) && typeof d.input !== 'string') out.push('input must be an object (templated JSON)');
    return out;
  },
  condition: (d) => {
    if (typeof d.expression !== 'string' || !d.expression.trim()) return ['expression is required'];
    const err = checkSyntax(d.expression);
    return err ? [`expression: ${err}`] : [];
  },
  action: (d) => {
    const out: string[] = [];
    if (!ACTION_KINDS.includes(d.kind as never)) out.push(`kind must be one of ${ACTION_KINDS.join(', ')}`);
    if (d.config !== undefined && !isObj(d.config)) out.push('config must be an object');
    return out;
  },
  transform: (d) => (d.template === undefined ? ['template is required'] : []),
  end: () => [],
};

export interface ValidateOptions {
  /** Ids (or, for drafts, names) of the agent's tools; unknown references are errors when given. */
  toolIds?: Set<string>;
}

/** Five field cron (minute hour day month weekday) with numbers, ranges, lists, steps and *. */
export function isCron(expr: string): boolean {
  const parts = expr.trim().split(/\s+/);
  if (parts.length !== 5) return false;
  const ranges = [[0, 59], [0, 23], [1, 31], [1, 12], [0, 7]];
  return parts.every((p, i) => p.split(',').every((item) => {
    const m = /^(\*|(\d+)(-(\d+))?)(\/(\d+))?$/.exec(item);
    if (!m) return false;
    const [lo, hi] = ranges[i];
    const nums = [m[2], m[4], m[6]].filter((x) => x !== undefined).map(Number);
    if (m[6] !== undefined && Number(m[6]) < 1) return false;
    return [m[2], m[4]].filter((x) => x !== undefined).map(Number).every((n) => n >= lo && n <= hi) && nums.every((n) => Number.isInteger(n));
  }));
}

/** Normalizes and validates a graph. Returns the cleaned graph and every issue found. */
export function validateGraph(input: unknown, opts: ValidateOptions = {}): { graph: Graph; issues: GraphIssue[] } {
  const issues: GraphIssue[] = [];
  const graph: Graph = { nodes: [], edges: [] };
  if (!isObj(input)) return { graph, issues: [{ path: 'graph', message: 'graph must be an object with nodes and edges' }] };
  const nodes = Array.isArray(input.nodes) ? input.nodes : null;
  const edges = Array.isArray(input.edges) ? input.edges : input.edges === undefined ? [] : null;
  if (!nodes) issues.push({ path: 'graph.nodes', message: 'nodes must be a list' });
  if (!edges) issues.push({ path: 'graph.edges', message: 'edges must be a list' });
  if (!nodes || !edges) return { graph, issues };
  if (nodes.length > MAX_NODES) issues.push({ path: 'graph.nodes', message: `at most ${MAX_NODES} nodes` });
  if (edges.length > MAX_EDGES) issues.push({ path: 'graph.edges', message: `at most ${MAX_EDGES} edges` });

  const ids = new Set<string>();
  nodes.forEach((raw, i) => {
    const path = `graph.nodes[${i}]`;
    if (!isObj(raw)) return issues.push({ path, message: 'node must be an object' });
    const id = raw.id;
    if (typeof id !== 'string' || !ID.test(id)) return issues.push({ path: `${path}.id`, message: 'id must start with a letter and use letters, digits, _ or - (max 64)' });
    if (ids.has(id)) return issues.push({ path: `${path}.id`, message: `duplicate node id ${id}` });
    ids.add(id);
    const type = raw.type;
    if (typeof type !== 'string' || !(type in NODE_TYPES)) return issues.push({ path: `${path}.type`, message: `unknown node type ${String(type)}; use one of ${Object.keys(NODE_TYPES).join(', ')}` });
    const data = raw.data === undefined ? {} : raw.data;
    if (!isObj(data)) return issues.push({ path: `${path}.data`, message: 'data must be an object' });
    for (const m of NODE_TYPES[type](data, opts)) issues.push({ path: `${path}.data`, message: `${id}: ${m}` });
    const pos = isObj(raw.position) && typeof raw.position.x === 'number' && typeof raw.position.y === 'number' ? { x: raw.position.x, y: raw.position.y } : { x: 0, y: i * 120 };
    graph.nodes.push({ id, type, position: pos, data });
  });

  const edgeIds = new Set<string>();
  edges.forEach((raw, i) => {
    const path = `graph.edges[${i}]`;
    if (!isObj(raw)) return issues.push({ path, message: 'edge must be an object' });
    const id = typeof raw.id === 'string' && raw.id ? raw.id : `e${i}`;
    if (edgeIds.has(id)) return issues.push({ path: `${path}.id`, message: `duplicate edge id ${id}` });
    edgeIds.add(id);
    const { source, target } = raw;
    if (typeof source !== 'string' || !ids.has(source)) return issues.push({ path: `${path}.source`, message: `unknown source node ${String(source)}` });
    if (typeof target !== 'string' || !ids.has(target)) return issues.push({ path: `${path}.target`, message: `unknown target node ${String(target)}` });
    if (source === target) return issues.push({ path, message: 'an edge cannot connect a node to itself' });
    const sourceHandle = typeof raw.sourceHandle === 'string' ? raw.sourceHandle : null;
    graph.edges.push({ id, source, target, sourceHandle, label: typeof raw.label === 'string' ? raw.label : null });
  });

  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const triggers = graph.nodes.filter((n) => n.type === 'trigger');
  if (graph.nodes.length && triggers.length !== 1) issues.push({ path: 'graph.nodes', message: `a workflow needs exactly one trigger node (found ${triggers.length})` });
  if (!graph.nodes.length) issues.push({ path: 'graph.nodes', message: 'a workflow needs a trigger node' });
  for (const e of graph.edges) {
    const src = byId.get(e.source)!;
    const tgt = byId.get(e.target)!;
    if (tgt.type === 'trigger') issues.push({ path: `edge ${e.id}`, message: 'nothing can lead into the trigger' });
    if (src.type === 'end') issues.push({ path: `edge ${e.id}`, message: 'an end node has no outgoing edges' });
    if (src.type === 'condition' && e.sourceHandle !== 'true' && e.sourceHandle !== 'false') issues.push({ path: `edge ${e.id}`, message: 'edges leaving a condition need sourceHandle "true" or "false"' });
  }

  const order = topoOrder(graph);
  if (!order) issues.push({ path: 'graph.edges', message: 'the workflow has a cycle' });
  else if (triggers.length === 1) {
    const reach = reachable(graph, triggers[0].id);
    for (const n of graph.nodes) if (!reach.has(n.id)) issues.push({ path: `node ${n.id}`, message: `${n.id} cannot be reached from the trigger` });
  }
  return { graph, issues };
}

/** Kahn's algorithm. Null when the graph has a cycle. Ties keep the node list order. */
export function topoOrder(graph: Graph): string[] | null {
  const indeg = new Map(graph.nodes.map((n) => [n.id, 0]));
  for (const e of graph.edges) indeg.set(e.target, (indeg.get(e.target) ?? 0) + 1);
  const queue = graph.nodes.filter((n) => indeg.get(n.id) === 0).map((n) => n.id);
  const out: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    out.push(id);
    for (const e of graph.edges.filter((x) => x.source === id)) {
      const d = indeg.get(e.target)! - 1;
      indeg.set(e.target, d);
      if (d === 0) queue.push(e.target);
    }
  }
  return out.length === graph.nodes.length ? out : null;
}

export function reachable(graph: Graph, from: string): Set<string> {
  const seen = new Set([from]);
  const stack = [from];
  while (stack.length) {
    const id = stack.pop()!;
    for (const e of graph.edges) if (e.source === id && !seen.has(e.target)) { seen.add(e.target); stack.push(e.target); }
  }
  return seen;
}

/** The graph a run without a workflow uses: trigger -> agent -> end. */
export function implicitGraph(): Graph {
  return {
    nodes: [
      { id: 'trigger', type: 'trigger', position: { x: 0, y: 0 }, data: { source: 'api' } },
      { id: 'agent', type: 'agent', position: { x: 0, y: 120 }, data: { prompt: '{{trigger.prompt}}' } },
      { id: 'end', type: 'end', position: { x: 0, y: 240 }, data: { output: '{{steps.agent.output}}' } },
    ],
    edges: [
      { id: 'e1', source: 'trigger', target: 'agent' },
      { id: 'e2', source: 'agent', target: 'end' },
    ],
  };
}
