-- Maps every table, enum type and sequence to the prgd_ prefix (schema.prisma @@map).
-- Tables, types, sequences, constraints and indexes are renamed in place with ALTER ... RENAME,
-- never dropped, so existing data survives. Column names do not change.

-- Tables
ALTER TABLE "User" RENAME TO "prgd_users";
ALTER TABLE "EmailToken" RENAME TO "prgd_email_tokens";
ALTER TABLE "Team" RENAME TO "prgd_teams";
ALTER TABLE "TeamMember" RENAME TO "prgd_team_members";
ALTER TABLE "Invitation" RENAME TO "prgd_invitations";
ALTER TABLE "Project" RENAME TO "prgd_projects";
ALTER TABLE "SshKey" RENAME TO "prgd_ssh_keys";
ALTER TABLE "ApiToken" RENAME TO "prgd_api_tokens";
ALTER TABLE "Approval" RENAME TO "prgd_approvals";
ALTER TABLE "Region" RENAME TO "prgd_regions";
ALTER TABLE "Host" RENAME TO "prgd_hosts";
ALTER TABLE "Size" RENAME TO "prgd_sizes";
ALTER TABLE "Image" RENAME TO "prgd_images";
ALTER TABLE "Server" RENAME TO "prgd_servers";
ALTER TABLE "ServerAction" RENAME TO "prgd_server_actions";
ALTER TABLE "Snapshot" RENAME TO "prgd_snapshots";
ALTER TABLE "IpBlock" RENAME TO "prgd_ip_blocks";
ALTER TABLE "PublicIp" RENAME TO "prgd_public_ips";
ALTER TABLE "PrivateNetwork" RENAME TO "prgd_private_networks";
ALTER TABLE "PrivateIp" RENAME TO "prgd_private_ips";
ALTER TABLE "Firewall" RENAME TO "prgd_firewalls";
ALTER TABLE "FirewallRule" RENAME TO "prgd_firewall_rules";
ALTER TABLE "FirewallServer" RENAME TO "prgd_firewall_servers";
ALTER TABLE "MarketplaceApp" RENAME TO "prgd_marketplace_apps";
ALTER TABLE "UsageEvent" RENAME TO "prgd_usage_events";
ALTER TABLE "UsageRecord" RENAME TO "prgd_usage_records";
ALTER TABLE "FxRate" RENAME TO "prgd_fx_rates";
ALTER TABLE "Price" RENAME TO "prgd_prices";
ALTER TABLE "Invoice" RENAME TO "prgd_invoices";
ALTER TABLE "Credit" RENAME TO "prgd_credits";
ALTER TABLE "Payment" RENAME TO "prgd_payments";
ALTER TABLE "CreditNote" RENAME TO "prgd_credit_notes";
ALTER TABLE "AbuseFlag" RENAME TO "prgd_abuse_flags";
ALTER TABLE "AuditLog" RENAME TO "prgd_audit_logs";
ALTER TABLE "Webhook" RENAME TO "prgd_webhooks";
ALTER TABLE "WebhookDelivery" RENAME TO "prgd_webhook_deliveries";
ALTER TABLE "Deployment" RENAME TO "prgd_deployments";
ALTER TABLE "GithubInstallation" RENAME TO "prgd_github_installations";
ALTER TABLE "ProductInterest" RENAME TO "prgd_product_interests";
ALTER TABLE "IdempotencyKey" RENAME TO "prgd_idempotency_keys";
ALTER TABLE "MetricSample" RENAME TO "prgd_metric_samples";
ALTER TABLE "MetricHourly" RENAME TO "prgd_metric_hourly";
ALTER TABLE "MetricCursor" RENAME TO "prgd_metric_cursors";
ALTER TABLE "AlertPolicy" RENAME TO "prgd_alert_policies";
ALTER TABLE "AlertIncident" RENAME TO "prgd_alert_incidents";
ALTER TABLE "Volume" RENAME TO "prgd_volumes";
ALTER TABLE "Certificate" RENAME TO "prgd_certificates";
ALTER TABLE "LoadBalancer" RENAME TO "prgd_load_balancers";
ALTER TABLE "LoadBalancerNode" RENAME TO "prgd_load_balancer_nodes";
ALTER TABLE "LoadBalancerTarget" RENAME TO "prgd_load_balancer_targets";
ALTER TABLE "DnsZone" RENAME TO "prgd_dns_zones";
ALTER TABLE "DnsRecord" RENAME TO "prgd_dns_records";
ALTER TABLE "Bucket" RENAME TO "prgd_buckets";
ALTER TABLE "StorageKey" RENAME TO "prgd_storage_keys";
ALTER TABLE "DbCluster" RENAME TO "prgd_db_clusters";
ALTER TABLE "DbNode" RENAME TO "prgd_db_nodes";
ALTER TABLE "DbUser" RENAME TO "prgd_db_users";
ALTER TABLE "DbDatabase" RENAME TO "prgd_db_databases";
ALTER TABLE "DbBackup" RENAME TO "prgd_db_backups";
ALTER TABLE "Ticket" RENAME TO "prgd_tickets";
ALTER TABLE "TicketMessage" RENAME TO "prgd_ticket_messages";
ALTER TABLE "KubeCluster" RENAME TO "prgd_kube_clusters";
ALTER TABLE "KubeNodePool" RENAME TO "prgd_kube_node_pools";
ALTER TABLE "KubeNode" RENAME TO "prgd_kube_nodes";
ALTER TABLE "AppHost" RENAME TO "prgd_app_hosts";
ALTER TABLE "PlatformApp" RENAME TO "prgd_platform_apps";
ALTER TABLE "AppDeploy" RENAME TO "prgd_app_deploys";
ALTER TABLE "Session" RENAME TO "prgd_sessions";
ALTER TABLE "ManagedPlan" RENAME TO "prgd_managed_plans";
ALTER TABLE "ManagedContract" RENAME TO "prgd_managed_contracts";
ALTER TABLE "OnboardingItem" RENAME TO "prgd_onboarding_items";
ALTER TABLE "ManagedAsset" RENAME TO "prgd_managed_assets";
ALTER TABLE "Responsibility" RENAME TO "prgd_responsibilities";
ALTER TABLE "Alert" RENAME TO "prgd_alerts";
ALTER TABLE "OnCallShift" RENAME TO "prgd_on_call_shifts";
ALTER TABLE "Page" RENAME TO "prgd_pages";
ALTER TABLE "MaintenanceTask" RENAME TO "prgd_maintenance_tasks";
ALTER TABLE "MaintenanceRun" RENAME TO "prgd_maintenance_runs";
ALTER TABLE "WorkLog" RENAME TO "prgd_work_logs";
ALTER TABLE "Runbook" RENAME TO "prgd_runbooks";
ALTER TABLE "MonthlyReport" RENAME TO "prgd_monthly_reports";
ALTER TABLE "Holiday" RENAME TO "prgd_holidays";

-- Enum types
ALTER TYPE "TeamRole" RENAME TO "prgd_team_role";
ALTER TYPE "Currency" RENAME TO "prgd_currency";
ALTER TYPE "AccountStatus" RENAME TO "prgd_account_status";
ALTER TYPE "ApprovalStatus" RENAME TO "prgd_approval_status";
ALTER TYPE "HostStatus" RENAME TO "prgd_host_status";
ALTER TYPE "ServerStatus" RENAME TO "prgd_server_status";
ALTER TYPE "ImageKind" RENAME TO "prgd_image_kind";
ALTER TYPE "ActionType" RENAME TO "prgd_action_type";
ALTER TYPE "ActionStatus" RENAME TO "prgd_action_status";
ALTER TYPE "SnapshotStatus" RENAME TO "prgd_snapshot_status";
ALTER TYPE "SnapshotKind" RENAME TO "prgd_snapshot_kind";
ALTER TYPE "IpStatus" RENAME TO "prgd_ip_status";
ALTER TYPE "FirewallDirection" RENAME TO "prgd_firewall_direction";
ALTER TYPE "FirewallProtocol" RENAME TO "prgd_firewall_protocol";
ALTER TYPE "AppStatus" RENAME TO "prgd_app_status";
ALTER TYPE "ResourceType" RENAME TO "prgd_resource_type";
ALTER TYPE "InvoiceStatus" RENAME TO "prgd_invoice_status";
ALTER TYPE "CreditKind" RENAME TO "prgd_credit_kind";
ALTER TYPE "PaymentProvider" RENAME TO "prgd_payment_provider";
ALTER TYPE "PaymentStatus" RENAME TO "prgd_payment_status";
ALTER TYPE "AbuseKind" RENAME TO "prgd_abuse_kind";
ALTER TYPE "DeployStatus" RENAME TO "prgd_deploy_status";
ALTER TYPE "AlertMetric" RENAME TO "prgd_alert_metric";
ALTER TYPE "AlertComparator" RENAME TO "prgd_alert_comparator";
ALTER TYPE "VolumeStatus" RENAME TO "prgd_volume_status";
ALTER TYPE "LoadBalancerStatus" RENAME TO "prgd_load_balancer_status";
ALTER TYPE "LbAlgorithm" RENAME TO "prgd_lb_algorithm";
ALTER TYPE "CertificateType" RENAME TO "prgd_certificate_type";
ALTER TYPE "DnsZoneStatus" RENAME TO "prgd_dns_zone_status";
ALTER TYPE "DnsRecordType" RENAME TO "prgd_dns_record_type";
ALTER TYPE "BucketStatus" RENAME TO "prgd_bucket_status";
ALTER TYPE "DbEngine" RENAME TO "prgd_db_engine";
ALTER TYPE "DbClusterStatus" RENAME TO "prgd_db_cluster_status";
ALTER TYPE "DbBackupStatus" RENAME TO "prgd_db_backup_status";
ALTER TYPE "SupportPlan" RENAME TO "prgd_support_plan";
ALTER TYPE "TicketStatus" RENAME TO "prgd_ticket_status";
ALTER TYPE "TicketPriority" RENAME TO "prgd_ticket_priority";
ALTER TYPE "KubeClusterStatus" RENAME TO "prgd_kube_cluster_status";
ALTER TYPE "AppHostStatus" RENAME TO "prgd_app_host_status";
ALTER TYPE "PlatformAppStatus" RENAME TO "prgd_platform_app_status";
ALTER TYPE "AppDeployStatus" RENAME TO "prgd_app_deploy_status";
ALTER TYPE "ManagedCoverage" RENAME TO "prgd_managed_coverage";
ALTER TYPE "ManagedContractStatus" RENAME TO "prgd_managed_contract_status";
ALTER TYPE "ManagedCalendar" RENAME TO "prgd_managed_calendar";
ALTER TYPE "ManagedPriority" RENAME TO "prgd_managed_priority";
ALTER TYPE "ManagedAssetKind" RENAME TO "prgd_managed_asset_kind";
ALTER TYPE "ManagedAssetStatus" RENAME TO "prgd_managed_asset_status";
ALTER TYPE "ManagedAssetHealth" RENAME TO "prgd_managed_asset_health";
ALTER TYPE "ResponsibilityOwner" RENAME TO "prgd_responsibility_owner";
ALTER TYPE "AlertSeverity" RENAME TO "prgd_alert_severity";
ALTER TYPE "AlertStatus" RENAME TO "prgd_alert_status";
ALTER TYPE "OnCallRole" RENAME TO "prgd_on_call_role";
ALTER TYPE "PageChannel" RENAME TO "prgd_page_channel";
ALTER TYPE "MaintenanceKind" RENAME TO "prgd_maintenance_kind";
ALTER TYPE "MaintenanceRunStatus" RENAME TO "prgd_maintenance_run_status";
ALTER TYPE "MonthlyReportStatus" RENAME TO "prgd_monthly_report_status";

-- Sequences
ALTER SEQUENCE "UsageEvent_id_seq" RENAME TO "prgd_usage_events_id_seq";
ALTER SEQUENCE "Ticket_number_seq" RENAME TO "prgd_tickets_number_seq";
ALTER SEQUENCE "credit_note_number_seq" RENAME TO "prgd_credit_note_number_seq";
ALTER SEQUENCE "invoice_number_seq" RENAME TO "prgd_invoice_number_seq";

-- Primary keys, unique constraints and foreign keys
ALTER TABLE "prgd_abuse_flags" RENAME CONSTRAINT "AbuseFlag_pkey" TO "prgd_abuse_flags_pkey";
ALTER TABLE "prgd_abuse_flags" RENAME CONSTRAINT "AbuseFlag_teamId_fkey" TO "prgd_abuse_flags_teamId_fkey";
ALTER TABLE "prgd_alerts" RENAME CONSTRAINT "Alert_acknowledgedById_fkey" TO "prgd_alerts_acknowledgedById_fkey";
ALTER TABLE "prgd_alerts" RENAME CONSTRAINT "Alert_assetId_fkey" TO "prgd_alerts_assetId_fkey";
ALTER TABLE "prgd_alerts" RENAME CONSTRAINT "Alert_contractId_fkey" TO "prgd_alerts_contractId_fkey";
ALTER TABLE "prgd_alerts" RENAME CONSTRAINT "Alert_pkey" TO "prgd_alerts_pkey";
ALTER TABLE "prgd_alerts" RENAME CONSTRAINT "Alert_ticketId_fkey" TO "prgd_alerts_ticketId_fkey";
ALTER TABLE "prgd_alert_incidents" RENAME CONSTRAINT "AlertIncident_pkey" TO "prgd_alert_incidents_pkey";
ALTER TABLE "prgd_alert_incidents" RENAME CONSTRAINT "AlertIncident_policyId_fkey" TO "prgd_alert_incidents_policyId_fkey";
ALTER TABLE "prgd_alert_policies" RENAME CONSTRAINT "AlertPolicy_pkey" TO "prgd_alert_policies_pkey";
ALTER TABLE "prgd_alert_policies" RENAME CONSTRAINT "AlertPolicy_teamId_fkey" TO "prgd_alert_policies_teamId_fkey";
ALTER TABLE "prgd_api_tokens" RENAME CONSTRAINT "ApiToken_pkey" TO "prgd_api_tokens_pkey";
ALTER TABLE "prgd_api_tokens" RENAME CONSTRAINT "ApiToken_projectId_fkey" TO "prgd_api_tokens_projectId_fkey";
ALTER TABLE "prgd_api_tokens" RENAME CONSTRAINT "ApiToken_teamId_fkey" TO "prgd_api_tokens_teamId_fkey";
ALTER TABLE "prgd_api_tokens" RENAME CONSTRAINT "ApiToken_userId_fkey" TO "prgd_api_tokens_userId_fkey";
ALTER TABLE "prgd_app_deploys" RENAME CONSTRAINT "AppDeploy_appId_fkey" TO "prgd_app_deploys_appId_fkey";
ALTER TABLE "prgd_app_deploys" RENAME CONSTRAINT "AppDeploy_pkey" TO "prgd_app_deploys_pkey";
ALTER TABLE "prgd_app_hosts" RENAME CONSTRAINT "AppHost_pkey" TO "prgd_app_hosts_pkey";
ALTER TABLE "prgd_app_hosts" RENAME CONSTRAINT "AppHost_regionId_fkey" TO "prgd_app_hosts_regionId_fkey";
ALTER TABLE "prgd_app_hosts" RENAME CONSTRAINT "AppHost_serverId_fkey" TO "prgd_app_hosts_serverId_fkey";
ALTER TABLE "prgd_approvals" RENAME CONSTRAINT "Approval_decidedById_fkey" TO "prgd_approvals_decidedById_fkey";
ALTER TABLE "prgd_approvals" RENAME CONSTRAINT "Approval_pkey" TO "prgd_approvals_pkey";
ALTER TABLE "prgd_approvals" RENAME CONSTRAINT "Approval_teamId_fkey" TO "prgd_approvals_teamId_fkey";
ALTER TABLE "prgd_approvals" RENAME CONSTRAINT "Approval_tokenId_fkey" TO "prgd_approvals_tokenId_fkey";
ALTER TABLE "prgd_audit_logs" RENAME CONSTRAINT "AuditLog_pkey" TO "prgd_audit_logs_pkey";
ALTER TABLE "prgd_audit_logs" RENAME CONSTRAINT "AuditLog_userId_fkey" TO "prgd_audit_logs_userId_fkey";
ALTER TABLE "prgd_buckets" RENAME CONSTRAINT "Bucket_pkey" TO "prgd_buckets_pkey";
ALTER TABLE "prgd_buckets" RENAME CONSTRAINT "Bucket_projectId_fkey" TO "prgd_buckets_projectId_fkey";
ALTER TABLE "prgd_buckets" RENAME CONSTRAINT "Bucket_regionId_fkey" TO "prgd_buckets_regionId_fkey";
ALTER TABLE "prgd_certificates" RENAME CONSTRAINT "Certificate_pkey" TO "prgd_certificates_pkey";
ALTER TABLE "prgd_certificates" RENAME CONSTRAINT "Certificate_projectId_fkey" TO "prgd_certificates_projectId_fkey";
ALTER TABLE "prgd_credits" RENAME CONSTRAINT "Credit_pkey" TO "prgd_credits_pkey";
ALTER TABLE "prgd_credits" RENAME CONSTRAINT "Credit_teamId_fkey" TO "prgd_credits_teamId_fkey";
ALTER TABLE "prgd_credit_notes" RENAME CONSTRAINT "CreditNote_invoiceId_fkey" TO "prgd_credit_notes_invoiceId_fkey";
ALTER TABLE "prgd_credit_notes" RENAME CONSTRAINT "CreditNote_pkey" TO "prgd_credit_notes_pkey";
ALTER TABLE "prgd_credit_notes" RENAME CONSTRAINT "CreditNote_teamId_fkey" TO "prgd_credit_notes_teamId_fkey";
ALTER TABLE "prgd_db_backups" RENAME CONSTRAINT "DbBackup_clusterId_fkey" TO "prgd_db_backups_clusterId_fkey";
ALTER TABLE "prgd_db_backups" RENAME CONSTRAINT "DbBackup_pkey" TO "prgd_db_backups_pkey";
ALTER TABLE "prgd_db_clusters" RENAME CONSTRAINT "DbCluster_pkey" TO "prgd_db_clusters_pkey";
ALTER TABLE "prgd_db_clusters" RENAME CONSTRAINT "DbCluster_projectId_fkey" TO "prgd_db_clusters_projectId_fkey";
ALTER TABLE "prgd_db_clusters" RENAME CONSTRAINT "DbCluster_publicIpId_fkey" TO "prgd_db_clusters_publicIpId_fkey";
ALTER TABLE "prgd_db_clusters" RENAME CONSTRAINT "DbCluster_regionId_fkey" TO "prgd_db_clusters_regionId_fkey";
ALTER TABLE "prgd_db_clusters" RENAME CONSTRAINT "DbCluster_sizeId_fkey" TO "prgd_db_clusters_sizeId_fkey";
ALTER TABLE "prgd_db_databases" RENAME CONSTRAINT "DbDatabase_clusterId_fkey" TO "prgd_db_databases_clusterId_fkey";
ALTER TABLE "prgd_db_databases" RENAME CONSTRAINT "DbDatabase_pkey" TO "prgd_db_databases_pkey";
ALTER TABLE "prgd_db_nodes" RENAME CONSTRAINT "DbNode_clusterId_fkey" TO "prgd_db_nodes_clusterId_fkey";
ALTER TABLE "prgd_db_nodes" RENAME CONSTRAINT "DbNode_pkey" TO "prgd_db_nodes_pkey";
ALTER TABLE "prgd_db_nodes" RENAME CONSTRAINT "DbNode_serverId_fkey" TO "prgd_db_nodes_serverId_fkey";
ALTER TABLE "prgd_db_users" RENAME CONSTRAINT "DbUser_clusterId_fkey" TO "prgd_db_users_clusterId_fkey";
ALTER TABLE "prgd_db_users" RENAME CONSTRAINT "DbUser_pkey" TO "prgd_db_users_pkey";
ALTER TABLE "prgd_deployments" RENAME CONSTRAINT "Deployment_installationId_fkey" TO "prgd_deployments_installationId_fkey";
ALTER TABLE "prgd_deployments" RENAME CONSTRAINT "Deployment_pkey" TO "prgd_deployments_pkey";
ALTER TABLE "prgd_deployments" RENAME CONSTRAINT "Deployment_projectId_fkey" TO "prgd_deployments_projectId_fkey";
ALTER TABLE "prgd_deployments" RENAME CONSTRAINT "Deployment_serverId_fkey" TO "prgd_deployments_serverId_fkey";
ALTER TABLE "prgd_dns_records" RENAME CONSTRAINT "DnsRecord_pkey" TO "prgd_dns_records_pkey";
ALTER TABLE "prgd_dns_records" RENAME CONSTRAINT "DnsRecord_zoneId_fkey" TO "prgd_dns_records_zoneId_fkey";
ALTER TABLE "prgd_dns_zones" RENAME CONSTRAINT "DnsZone_pkey" TO "prgd_dns_zones_pkey";
ALTER TABLE "prgd_dns_zones" RENAME CONSTRAINT "DnsZone_projectId_fkey" TO "prgd_dns_zones_projectId_fkey";
ALTER TABLE "prgd_email_tokens" RENAME CONSTRAINT "EmailToken_pkey" TO "prgd_email_tokens_pkey";
ALTER TABLE "prgd_email_tokens" RENAME CONSTRAINT "EmailToken_userId_fkey" TO "prgd_email_tokens_userId_fkey";
ALTER TABLE "prgd_firewalls" RENAME CONSTRAINT "Firewall_pkey" TO "prgd_firewalls_pkey";
ALTER TABLE "prgd_firewalls" RENAME CONSTRAINT "Firewall_projectId_fkey" TO "prgd_firewalls_projectId_fkey";
ALTER TABLE "prgd_firewall_rules" RENAME CONSTRAINT "FirewallRule_firewallId_fkey" TO "prgd_firewall_rules_firewallId_fkey";
ALTER TABLE "prgd_firewall_rules" RENAME CONSTRAINT "FirewallRule_pkey" TO "prgd_firewall_rules_pkey";
ALTER TABLE "prgd_firewall_servers" RENAME CONSTRAINT "FirewallServer_firewallId_fkey" TO "prgd_firewall_servers_firewallId_fkey";
ALTER TABLE "prgd_firewall_servers" RENAME CONSTRAINT "FirewallServer_pkey" TO "prgd_firewall_servers_pkey";
ALTER TABLE "prgd_firewall_servers" RENAME CONSTRAINT "FirewallServer_serverId_fkey" TO "prgd_firewall_servers_serverId_fkey";
ALTER TABLE "prgd_fx_rates" RENAME CONSTRAINT "FxRate_pkey" TO "prgd_fx_rates_pkey";
ALTER TABLE "prgd_github_installations" RENAME CONSTRAINT "GithubInstallation_pkey" TO "prgd_github_installations_pkey";
ALTER TABLE "prgd_github_installations" RENAME CONSTRAINT "GithubInstallation_teamId_fkey" TO "prgd_github_installations_teamId_fkey";
ALTER TABLE "prgd_holidays" RENAME CONSTRAINT "Holiday_pkey" TO "prgd_holidays_pkey";
ALTER TABLE "prgd_hosts" RENAME CONSTRAINT "Host_pkey" TO "prgd_hosts_pkey";
ALTER TABLE "prgd_hosts" RENAME CONSTRAINT "Host_regionId_fkey" TO "prgd_hosts_regionId_fkey";
ALTER TABLE "prgd_idempotency_keys" RENAME CONSTRAINT "IdempotencyKey_pkey" TO "prgd_idempotency_keys_pkey";
ALTER TABLE "prgd_images" RENAME CONSTRAINT "Image_pkey" TO "prgd_images_pkey";
ALTER TABLE "prgd_images" RENAME CONSTRAINT "Image_regionId_fkey" TO "prgd_images_regionId_fkey";
ALTER TABLE "prgd_invitations" RENAME CONSTRAINT "Invitation_pkey" TO "prgd_invitations_pkey";
ALTER TABLE "prgd_invitations" RENAME CONSTRAINT "Invitation_teamId_fkey" TO "prgd_invitations_teamId_fkey";
ALTER TABLE "prgd_invoices" RENAME CONSTRAINT "Invoice_pkey" TO "prgd_invoices_pkey";
ALTER TABLE "prgd_invoices" RENAME CONSTRAINT "Invoice_teamId_fkey" TO "prgd_invoices_teamId_fkey";
ALTER TABLE "prgd_ip_blocks" RENAME CONSTRAINT "IpBlock_pkey" TO "prgd_ip_blocks_pkey";
ALTER TABLE "prgd_ip_blocks" RENAME CONSTRAINT "IpBlock_regionId_fkey" TO "prgd_ip_blocks_regionId_fkey";
ALTER TABLE "prgd_kube_clusters" RENAME CONSTRAINT "KubeCluster_controlSizeId_fkey" TO "prgd_kube_clusters_controlSizeId_fkey";
ALTER TABLE "prgd_kube_clusters" RENAME CONSTRAINT "KubeCluster_pkey" TO "prgd_kube_clusters_pkey";
ALTER TABLE "prgd_kube_clusters" RENAME CONSTRAINT "KubeCluster_projectId_fkey" TO "prgd_kube_clusters_projectId_fkey";
ALTER TABLE "prgd_kube_clusters" RENAME CONSTRAINT "KubeCluster_publicIpId_fkey" TO "prgd_kube_clusters_publicIpId_fkey";
ALTER TABLE "prgd_kube_clusters" RENAME CONSTRAINT "KubeCluster_regionId_fkey" TO "prgd_kube_clusters_regionId_fkey";
ALTER TABLE "prgd_kube_nodes" RENAME CONSTRAINT "KubeNode_clusterId_fkey" TO "prgd_kube_nodes_clusterId_fkey";
ALTER TABLE "prgd_kube_nodes" RENAME CONSTRAINT "KubeNode_pkey" TO "prgd_kube_nodes_pkey";
ALTER TABLE "prgd_kube_nodes" RENAME CONSTRAINT "KubeNode_poolId_fkey" TO "prgd_kube_nodes_poolId_fkey";
ALTER TABLE "prgd_kube_nodes" RENAME CONSTRAINT "KubeNode_serverId_fkey" TO "prgd_kube_nodes_serverId_fkey";
ALTER TABLE "prgd_kube_node_pools" RENAME CONSTRAINT "KubeNodePool_clusterId_fkey" TO "prgd_kube_node_pools_clusterId_fkey";
ALTER TABLE "prgd_kube_node_pools" RENAME CONSTRAINT "KubeNodePool_pkey" TO "prgd_kube_node_pools_pkey";
ALTER TABLE "prgd_kube_node_pools" RENAME CONSTRAINT "KubeNodePool_sizeId_fkey" TO "prgd_kube_node_pools_sizeId_fkey";
ALTER TABLE "prgd_load_balancers" RENAME CONSTRAINT "LoadBalancer_pkey" TO "prgd_load_balancers_pkey";
ALTER TABLE "prgd_load_balancers" RENAME CONSTRAINT "LoadBalancer_projectId_fkey" TO "prgd_load_balancers_projectId_fkey";
ALTER TABLE "prgd_load_balancers" RENAME CONSTRAINT "LoadBalancer_publicIpId_fkey" TO "prgd_load_balancers_publicIpId_fkey";
ALTER TABLE "prgd_load_balancers" RENAME CONSTRAINT "LoadBalancer_regionId_fkey" TO "prgd_load_balancers_regionId_fkey";
ALTER TABLE "prgd_load_balancer_nodes" RENAME CONSTRAINT "LoadBalancerNode_loadBalancerId_fkey" TO "prgd_load_balancer_nodes_loadBalancerId_fkey";
ALTER TABLE "prgd_load_balancer_nodes" RENAME CONSTRAINT "LoadBalancerNode_pkey" TO "prgd_load_balancer_nodes_pkey";
ALTER TABLE "prgd_load_balancer_nodes" RENAME CONSTRAINT "LoadBalancerNode_serverId_fkey" TO "prgd_load_balancer_nodes_serverId_fkey";
ALTER TABLE "prgd_load_balancer_targets" RENAME CONSTRAINT "LoadBalancerTarget_loadBalancerId_fkey" TO "prgd_load_balancer_targets_loadBalancerId_fkey";
ALTER TABLE "prgd_load_balancer_targets" RENAME CONSTRAINT "LoadBalancerTarget_pkey" TO "prgd_load_balancer_targets_pkey";
ALTER TABLE "prgd_load_balancer_targets" RENAME CONSTRAINT "LoadBalancerTarget_serverId_fkey" TO "prgd_load_balancer_targets_serverId_fkey";
ALTER TABLE "prgd_maintenance_runs" RENAME CONSTRAINT "MaintenanceRun_pkey" TO "prgd_maintenance_runs_pkey";
ALTER TABLE "prgd_maintenance_runs" RENAME CONSTRAINT "MaintenanceRun_taskId_fkey" TO "prgd_maintenance_runs_taskId_fkey";
ALTER TABLE "prgd_maintenance_runs" RENAME CONSTRAINT "MaintenanceRun_ticketId_fkey" TO "prgd_maintenance_runs_ticketId_fkey";
ALTER TABLE "prgd_maintenance_tasks" RENAME CONSTRAINT "MaintenanceTask_assetId_fkey" TO "prgd_maintenance_tasks_assetId_fkey";
ALTER TABLE "prgd_maintenance_tasks" RENAME CONSTRAINT "MaintenanceTask_contractId_fkey" TO "prgd_maintenance_tasks_contractId_fkey";
ALTER TABLE "prgd_maintenance_tasks" RENAME CONSTRAINT "MaintenanceTask_pkey" TO "prgd_maintenance_tasks_pkey";
ALTER TABLE "prgd_managed_assets" RENAME CONSTRAINT "ManagedAsset_contractId_fkey" TO "prgd_managed_assets_contractId_fkey";
ALTER TABLE "prgd_managed_assets" RENAME CONSTRAINT "ManagedAsset_pkey" TO "prgd_managed_assets_pkey";
ALTER TABLE "prgd_managed_assets" RENAME CONSTRAINT "ManagedAsset_serverId_fkey" TO "prgd_managed_assets_serverId_fkey";
ALTER TABLE "prgd_managed_contracts" RENAME CONSTRAINT "ManagedContract_pkey" TO "prgd_managed_contracts_pkey";
ALTER TABLE "prgd_managed_contracts" RENAME CONSTRAINT "ManagedContract_planId_fkey" TO "prgd_managed_contracts_planId_fkey";
ALTER TABLE "prgd_managed_contracts" RENAME CONSTRAINT "ManagedContract_signedById_fkey" TO "prgd_managed_contracts_signedById_fkey";
ALTER TABLE "prgd_managed_contracts" RENAME CONSTRAINT "ManagedContract_teamId_fkey" TO "prgd_managed_contracts_teamId_fkey";
ALTER TABLE "prgd_managed_plans" RENAME CONSTRAINT "ManagedPlan_pkey" TO "prgd_managed_plans_pkey";
ALTER TABLE "prgd_marketplace_apps" RENAME CONSTRAINT "MarketplaceApp_imageId_fkey" TO "prgd_marketplace_apps_imageId_fkey";
ALTER TABLE "prgd_marketplace_apps" RENAME CONSTRAINT "MarketplaceApp_pkey" TO "prgd_marketplace_apps_pkey";
ALTER TABLE "prgd_metric_cursors" RENAME CONSTRAINT "MetricCursor_pkey" TO "prgd_metric_cursors_pkey";
ALTER TABLE "prgd_metric_hourly" RENAME CONSTRAINT "MetricHourly_pkey" TO "prgd_metric_hourly_pkey";
ALTER TABLE "prgd_metric_samples" RENAME CONSTRAINT "MetricSample_pkey" TO "prgd_metric_samples_pkey";
ALTER TABLE "prgd_monthly_reports" RENAME CONSTRAINT "MonthlyReport_contractId_fkey" TO "prgd_monthly_reports_contractId_fkey";
ALTER TABLE "prgd_monthly_reports" RENAME CONSTRAINT "MonthlyReport_pkey" TO "prgd_monthly_reports_pkey";
ALTER TABLE "prgd_on_call_shifts" RENAME CONSTRAINT "OnCallShift_pkey" TO "prgd_on_call_shifts_pkey";
ALTER TABLE "prgd_on_call_shifts" RENAME CONSTRAINT "OnCallShift_userId_fkey" TO "prgd_on_call_shifts_userId_fkey";
ALTER TABLE "prgd_onboarding_items" RENAME CONSTRAINT "OnboardingItem_contractId_fkey" TO "prgd_onboarding_items_contractId_fkey";
ALTER TABLE "prgd_onboarding_items" RENAME CONSTRAINT "OnboardingItem_doneById_fkey" TO "prgd_onboarding_items_doneById_fkey";
ALTER TABLE "prgd_onboarding_items" RENAME CONSTRAINT "OnboardingItem_pkey" TO "prgd_onboarding_items_pkey";
ALTER TABLE "prgd_pages" RENAME CONSTRAINT "Page_alertId_fkey" TO "prgd_pages_alertId_fkey";
ALTER TABLE "prgd_pages" RENAME CONSTRAINT "Page_pkey" TO "prgd_pages_pkey";
ALTER TABLE "prgd_pages" RENAME CONSTRAINT "Page_ticketId_fkey" TO "prgd_pages_ticketId_fkey";
ALTER TABLE "prgd_pages" RENAME CONSTRAINT "Page_userId_fkey" TO "prgd_pages_userId_fkey";
ALTER TABLE "prgd_payments" RENAME CONSTRAINT "Payment_invoiceId_fkey" TO "prgd_payments_invoiceId_fkey";
ALTER TABLE "prgd_payments" RENAME CONSTRAINT "Payment_pkey" TO "prgd_payments_pkey";
ALTER TABLE "prgd_payments" RENAME CONSTRAINT "Payment_teamId_fkey" TO "prgd_payments_teamId_fkey";
ALTER TABLE "prgd_platform_apps" RENAME CONSTRAINT "PlatformApp_hostId_fkey" TO "prgd_platform_apps_hostId_fkey";
ALTER TABLE "prgd_platform_apps" RENAME CONSTRAINT "PlatformApp_installationId_fkey" TO "prgd_platform_apps_installationId_fkey";
ALTER TABLE "prgd_platform_apps" RENAME CONSTRAINT "PlatformApp_pkey" TO "prgd_platform_apps_pkey";
ALTER TABLE "prgd_platform_apps" RENAME CONSTRAINT "PlatformApp_projectId_fkey" TO "prgd_platform_apps_projectId_fkey";
ALTER TABLE "prgd_platform_apps" RENAME CONSTRAINT "PlatformApp_regionId_fkey" TO "prgd_platform_apps_regionId_fkey";
ALTER TABLE "prgd_prices" RENAME CONSTRAINT "Price_pkey" TO "prgd_prices_pkey";
ALTER TABLE "prgd_prices" RENAME CONSTRAINT "Price_sizeId_fkey" TO "prgd_prices_sizeId_fkey";
ALTER TABLE "prgd_private_ips" RENAME CONSTRAINT "PrivateIp_networkId_fkey" TO "prgd_private_ips_networkId_fkey";
ALTER TABLE "prgd_private_ips" RENAME CONSTRAINT "PrivateIp_pkey" TO "prgd_private_ips_pkey";
ALTER TABLE "prgd_private_ips" RENAME CONSTRAINT "PrivateIp_serverId_fkey" TO "prgd_private_ips_serverId_fkey";
ALTER TABLE "prgd_private_networks" RENAME CONSTRAINT "PrivateNetwork_pkey" TO "prgd_private_networks_pkey";
ALTER TABLE "prgd_private_networks" RENAME CONSTRAINT "PrivateNetwork_projectId_fkey" TO "prgd_private_networks_projectId_fkey";
ALTER TABLE "prgd_private_networks" RENAME CONSTRAINT "PrivateNetwork_regionId_fkey" TO "prgd_private_networks_regionId_fkey";
ALTER TABLE "prgd_product_interests" RENAME CONSTRAINT "ProductInterest_pkey" TO "prgd_product_interests_pkey";
ALTER TABLE "prgd_projects" RENAME CONSTRAINT "Project_pkey" TO "prgd_projects_pkey";
ALTER TABLE "prgd_projects" RENAME CONSTRAINT "Project_teamId_fkey" TO "prgd_projects_teamId_fkey";
ALTER TABLE "prgd_public_ips" RENAME CONSTRAINT "PublicIp_blockId_fkey" TO "prgd_public_ips_blockId_fkey";
ALTER TABLE "prgd_public_ips" RENAME CONSTRAINT "PublicIp_pkey" TO "prgd_public_ips_pkey";
ALTER TABLE "prgd_public_ips" RENAME CONSTRAINT "PublicIp_projectId_fkey" TO "prgd_public_ips_projectId_fkey";
ALTER TABLE "prgd_public_ips" RENAME CONSTRAINT "PublicIp_regionId_fkey" TO "prgd_public_ips_regionId_fkey";
ALTER TABLE "prgd_public_ips" RENAME CONSTRAINT "PublicIp_serverId_fkey" TO "prgd_public_ips_serverId_fkey";
ALTER TABLE "prgd_regions" RENAME CONSTRAINT "Region_pkey" TO "prgd_regions_pkey";
ALTER TABLE "prgd_responsibilities" RENAME CONSTRAINT "Responsibility_contractId_fkey" TO "prgd_responsibilities_contractId_fkey";
ALTER TABLE "prgd_responsibilities" RENAME CONSTRAINT "Responsibility_pkey" TO "prgd_responsibilities_pkey";
ALTER TABLE "prgd_runbooks" RENAME CONSTRAINT "Runbook_pkey" TO "prgd_runbooks_pkey";
ALTER TABLE "prgd_runbooks" RENAME CONSTRAINT "Runbook_updatedById_fkey" TO "prgd_runbooks_updatedById_fkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_hostId_fkey" TO "prgd_servers_hostId_fkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_imageId_fkey" TO "prgd_servers_imageId_fkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_pkey" TO "prgd_servers_pkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_projectId_fkey" TO "prgd_servers_projectId_fkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_regionId_fkey" TO "prgd_servers_regionId_fkey";
ALTER TABLE "prgd_servers" RENAME CONSTRAINT "Server_sizeId_fkey" TO "prgd_servers_sizeId_fkey";
ALTER TABLE "prgd_server_actions" RENAME CONSTRAINT "ServerAction_pkey" TO "prgd_server_actions_pkey";
ALTER TABLE "prgd_server_actions" RENAME CONSTRAINT "ServerAction_serverId_fkey" TO "prgd_server_actions_serverId_fkey";
ALTER TABLE "prgd_sessions" RENAME CONSTRAINT "Session_pkey" TO "prgd_sessions_pkey";
ALTER TABLE "prgd_sessions" RENAME CONSTRAINT "Session_userId_fkey" TO "prgd_sessions_userId_fkey";
ALTER TABLE "prgd_sizes" RENAME CONSTRAINT "Size_pkey" TO "prgd_sizes_pkey";
ALTER TABLE "prgd_snapshots" RENAME CONSTRAINT "Snapshot_pkey" TO "prgd_snapshots_pkey";
ALTER TABLE "prgd_snapshots" RENAME CONSTRAINT "Snapshot_projectId_fkey" TO "prgd_snapshots_projectId_fkey";
ALTER TABLE "prgd_snapshots" RENAME CONSTRAINT "Snapshot_serverId_fkey" TO "prgd_snapshots_serverId_fkey";
ALTER TABLE "prgd_ssh_keys" RENAME CONSTRAINT "SshKey_pkey" TO "prgd_ssh_keys_pkey";
ALTER TABLE "prgd_ssh_keys" RENAME CONSTRAINT "SshKey_userId_fkey" TO "prgd_ssh_keys_userId_fkey";
ALTER TABLE "prgd_storage_keys" RENAME CONSTRAINT "StorageKey_pkey" TO "prgd_storage_keys_pkey";
ALTER TABLE "prgd_storage_keys" RENAME CONSTRAINT "StorageKey_projectId_fkey" TO "prgd_storage_keys_projectId_fkey";
ALTER TABLE "prgd_teams" RENAME CONSTRAINT "Team_pkey" TO "prgd_teams_pkey";
ALTER TABLE "prgd_team_members" RENAME CONSTRAINT "TeamMember_pkey" TO "prgd_team_members_pkey";
ALTER TABLE "prgd_team_members" RENAME CONSTRAINT "TeamMember_teamId_fkey" TO "prgd_team_members_teamId_fkey";
ALTER TABLE "prgd_team_members" RENAME CONSTRAINT "TeamMember_userId_fkey" TO "prgd_team_members_userId_fkey";
ALTER TABLE "prgd_tickets" RENAME CONSTRAINT "Ticket_assetId_fkey" TO "prgd_tickets_assetId_fkey";
ALTER TABLE "prgd_tickets" RENAME CONSTRAINT "Ticket_assigneeId_fkey" TO "prgd_tickets_assigneeId_fkey";
ALTER TABLE "prgd_tickets" RENAME CONSTRAINT "Ticket_contractId_fkey" TO "prgd_tickets_contractId_fkey";
ALTER TABLE "prgd_tickets" RENAME CONSTRAINT "Ticket_pkey" TO "prgd_tickets_pkey";
ALTER TABLE "prgd_ticket_messages" RENAME CONSTRAINT "TicketMessage_pkey" TO "prgd_ticket_messages_pkey";
ALTER TABLE "prgd_ticket_messages" RENAME CONSTRAINT "TicketMessage_ticketId_fkey" TO "prgd_ticket_messages_ticketId_fkey";
ALTER TABLE "prgd_usage_events" RENAME CONSTRAINT "UsageEvent_pkey" TO "prgd_usage_events_pkey";
ALTER TABLE "prgd_usage_records" RENAME CONSTRAINT "UsageRecord_invoiceId_fkey" TO "prgd_usage_records_invoiceId_fkey";
ALTER TABLE "prgd_usage_records" RENAME CONSTRAINT "UsageRecord_pkey" TO "prgd_usage_records_pkey";
ALTER TABLE "prgd_usage_records" RENAME CONSTRAINT "UsageRecord_priceId_fkey" TO "prgd_usage_records_priceId_fkey";
ALTER TABLE "prgd_usage_records" RENAME CONSTRAINT "UsageRecord_projectId_fkey" TO "prgd_usage_records_projectId_fkey";
ALTER TABLE "prgd_users" RENAME CONSTRAINT "User_pkey" TO "prgd_users_pkey";
ALTER TABLE "prgd_volumes" RENAME CONSTRAINT "Volume_pkey" TO "prgd_volumes_pkey";
ALTER TABLE "prgd_volumes" RENAME CONSTRAINT "Volume_projectId_fkey" TO "prgd_volumes_projectId_fkey";
ALTER TABLE "prgd_volumes" RENAME CONSTRAINT "Volume_regionId_fkey" TO "prgd_volumes_regionId_fkey";
ALTER TABLE "prgd_volumes" RENAME CONSTRAINT "Volume_serverId_fkey" TO "prgd_volumes_serverId_fkey";
ALTER TABLE "prgd_webhooks" RENAME CONSTRAINT "Webhook_pkey" TO "prgd_webhooks_pkey";
ALTER TABLE "prgd_webhooks" RENAME CONSTRAINT "Webhook_teamId_fkey" TO "prgd_webhooks_teamId_fkey";
ALTER TABLE "prgd_webhook_deliveries" RENAME CONSTRAINT "WebhookDelivery_pkey" TO "prgd_webhook_deliveries_pkey";
ALTER TABLE "prgd_webhook_deliveries" RENAME CONSTRAINT "WebhookDelivery_webhookId_fkey" TO "prgd_webhook_deliveries_webhookId_fkey";
ALTER TABLE "prgd_work_logs" RENAME CONSTRAINT "WorkLog_billedInvoiceId_fkey" TO "prgd_work_logs_billedInvoiceId_fkey";
ALTER TABLE "prgd_work_logs" RENAME CONSTRAINT "WorkLog_contractId_fkey" TO "prgd_work_logs_contractId_fkey";
ALTER TABLE "prgd_work_logs" RENAME CONSTRAINT "WorkLog_pkey" TO "prgd_work_logs_pkey";
ALTER TABLE "prgd_work_logs" RENAME CONSTRAINT "WorkLog_ticketId_fkey" TO "prgd_work_logs_ticketId_fkey";
ALTER TABLE "prgd_work_logs" RENAME CONSTRAINT "WorkLog_userId_fkey" TO "prgd_work_logs_userId_fkey";

-- Indexes
ALTER INDEX "AbuseFlag_teamId_resolvedAt_idx" RENAME TO "prgd_abuse_flags_teamId_resolvedAt_idx";
ALTER INDEX "Alert_assetId_startsAt_idx" RENAME TO "prgd_alerts_assetId_startsAt_idx";
ALTER INDEX "Alert_contractId_status_idx" RENAME TO "prgd_alerts_contractId_status_idx";
ALTER INDEX "Alert_openKey_key" RENAME TO "prgd_alerts_openKey_key";
ALTER INDEX "Alert_status_severity_idx" RENAME TO "prgd_alerts_status_severity_idx";
ALTER INDEX "AlertIncident_policyId_serverId_resolvedAt_idx" RENAME TO "prgd_alert_incidents_policyId_serverId_resolvedAt_idx";
ALTER INDEX "AlertIncident_teamId_resolvedAt_startedAt_idx" RENAME TO "prgd_alert_incidents_teamId_resolvedAt_startedAt_idx";
ALTER INDEX "AlertPolicy_teamId_idx" RENAME TO "prgd_alert_policies_teamId_idx";
ALTER INDEX "ApiToken_hash_key" RENAME TO "prgd_api_tokens_hash_key";
ALTER INDEX "AppDeploy_appId_startedAt_idx" RENAME TO "prgd_app_deploys_appId_startedAt_idx";
ALTER INDEX "AppHost_serverId_key" RENAME TO "prgd_app_hosts_serverId_key";
ALTER INDEX "Approval_teamId_status_createdAt_idx" RENAME TO "prgd_approvals_teamId_status_createdAt_idx";
ALTER INDEX "Approval_tokenId_status_idx" RENAME TO "prgd_approvals_tokenId_status_idx";
ALTER INDEX "AuditLog_teamId_at_idx" RENAME TO "prgd_audit_logs_teamId_at_idx";
ALTER INDEX "Bucket_name_live_key" RENAME TO "prgd_buckets_name_live_key";
ALTER INDEX "Bucket_projectId_idx" RENAME TO "prgd_buckets_projectId_idx";
ALTER INDEX "Certificate_projectId_idx" RENAME TO "prgd_certificates_projectId_idx";
ALTER INDEX "CreditNote_invoiceId_idx" RENAME TO "prgd_credit_notes_invoiceId_idx";
ALTER INDEX "CreditNote_number_key" RENAME TO "prgd_credit_notes_number_key";
ALTER INDEX "CreditNote_teamId_createdAt_idx" RENAME TO "prgd_credit_notes_teamId_createdAt_idx";
ALTER INDEX "DbBackup_clusterId_idx" RENAME TO "prgd_db_backups_clusterId_idx";
ALTER INDEX "DbCluster_projectId_idx" RENAME TO "prgd_db_clusters_projectId_idx";
ALTER INDEX "DbCluster_publicIpId_key" RENAME TO "prgd_db_clusters_publicIpId_key";
ALTER INDEX "DbDatabase_clusterId_name_key" RENAME TO "prgd_db_databases_clusterId_name_key";
ALTER INDEX "DbNode_serverId_key" RENAME TO "prgd_db_nodes_serverId_key";
ALTER INDEX "DbUser_clusterId_name_key" RENAME TO "prgd_db_users_clusterId_name_key";
ALTER INDEX "Deployment_projectId_idx" RENAME TO "prgd_deployments_projectId_idx";
ALTER INDEX "Deployment_repoFullName_branch_idx" RENAME TO "prgd_deployments_repoFullName_branch_idx";
ALTER INDEX "Deployment_serverId_key" RENAME TO "prgd_deployments_serverId_key";
ALTER INDEX "DnsRecord_zoneId_idx" RENAME TO "prgd_dns_records_zoneId_idx";
ALTER INDEX "DnsZone_name_live_key" RENAME TO "prgd_dns_zones_name_live_key";
ALTER INDEX "DnsZone_projectId_idx" RENAME TO "prgd_dns_zones_projectId_idx";
ALTER INDEX "EmailToken_tokenHash_key" RENAME TO "prgd_email_tokens_tokenHash_key";
ALTER INDEX "EmailToken_userId_kind_idx" RENAME TO "prgd_email_tokens_userId_kind_idx";
ALTER INDEX "FxRate_base_quote_at_idx" RENAME TO "prgd_fx_rates_base_quote_at_idx";
ALTER INDEX "GithubInstallation_installationId_key" RENAME TO "prgd_github_installations_installationId_key";
ALTER INDEX "GithubInstallation_teamId_idx" RENAME TO "prgd_github_installations_teamId_idx";
ALTER INDEX "Holiday_country_date_key" RENAME TO "prgd_holidays_country_date_key";
ALTER INDEX "Host_name_key" RENAME TO "prgd_hosts_name_key";
ALTER INDEX "IdempotencyKey_createdAt_idx" RENAME TO "prgd_idempotency_keys_createdAt_idx";
ALTER INDEX "Invitation_teamId_email_idx" RENAME TO "prgd_invitations_teamId_email_idx";
ALTER INDEX "Invitation_tokenHash_key" RENAME TO "prgd_invitations_tokenHash_key";
ALTER INDEX "Invoice_number_key" RENAME TO "prgd_invoices_number_key";
ALTER INDEX "Invoice_status_dueAt_idx" RENAME TO "prgd_invoices_status_dueAt_idx";
ALTER INDEX "Invoice_teamId_periodStart_periodEnd_key" RENAME TO "prgd_invoices_teamId_periodStart_periodEnd_key";
ALTER INDEX "IpBlock_cidr_key" RENAME TO "prgd_ip_blocks_cidr_key";
ALTER INDEX "KubeCluster_projectId_idx" RENAME TO "prgd_kube_clusters_projectId_idx";
ALTER INDEX "KubeCluster_publicIpId_key" RENAME TO "prgd_kube_clusters_publicIpId_key";
ALTER INDEX "KubeNode_clusterId_idx" RENAME TO "prgd_kube_nodes_clusterId_idx";
ALTER INDEX "KubeNode_serverId_key" RENAME TO "prgd_kube_nodes_serverId_key";
ALTER INDEX "KubeNodePool_clusterId_name_key" RENAME TO "prgd_kube_node_pools_clusterId_name_key";
ALTER INDEX "LoadBalancer_projectId_idx" RENAME TO "prgd_load_balancers_projectId_idx";
ALTER INDEX "LoadBalancer_publicIpId_key" RENAME TO "prgd_load_balancers_publicIpId_key";
ALTER INDEX "LoadBalancerNode_serverId_key" RENAME TO "prgd_load_balancer_nodes_serverId_key";
ALTER INDEX "LoadBalancerTarget_loadBalancerId_serverId_key" RENAME TO "prgd_load_balancer_targets_loadBalancerId_serverId_key";
ALTER INDEX "MaintenanceRun_status_idx" RENAME TO "prgd_maintenance_runs_status_idx";
ALTER INDEX "MaintenanceRun_taskId_createdAt_idx" RENAME TO "prgd_maintenance_runs_taskId_createdAt_idx";
ALTER INDEX "MaintenanceTask_contractId_idx" RENAME TO "prgd_maintenance_tasks_contractId_idx";
ALTER INDEX "MaintenanceTask_enabled_nextRunAt_idx" RENAME TO "prgd_maintenance_tasks_enabled_nextRunAt_idx";
ALTER INDEX "ManagedAsset_contractId_status_idx" RENAME TO "prgd_managed_assets_contractId_status_idx";
ALTER INDEX "ManagedAsset_heartbeatTokenHash_key" RENAME TO "prgd_managed_assets_heartbeatTokenHash_key";
ALTER INDEX "ManagedAsset_status_kind_lastHeartbeatAt_idx" RENAME TO "prgd_managed_assets_status_kind_lastHeartbeatAt_idx";
ALTER INDEX "ManagedContract_status_idx" RENAME TO "prgd_managed_contracts_status_idx";
ALTER INDEX "ManagedContract_teamId_status_idx" RENAME TO "prgd_managed_contracts_teamId_status_idx";
ALTER INDEX "ManagedPlan_code_key" RENAME TO "prgd_managed_plans_code_key";
ALTER INDEX "MarketplaceApp_imageId_key" RENAME TO "prgd_marketplace_apps_imageId_key";
ALTER INDEX "MarketplaceApp_slug_key" RENAME TO "prgd_marketplace_apps_slug_key";
ALTER INDEX "MetricSample_at_idx" RENAME TO "prgd_metric_samples_at_idx";
ALTER INDEX "MonthlyReport_contractId_period_key" RENAME TO "prgd_monthly_reports_contractId_period_key";
ALTER INDEX "OnCallShift_startsAt_endsAt_idx" RENAME TO "prgd_on_call_shifts_startsAt_endsAt_idx";
ALTER INDEX "OnCallShift_userId_startsAt_idx" RENAME TO "prgd_on_call_shifts_userId_startsAt_idx";
ALTER INDEX "OnboardingItem_contractId_key_key" RENAME TO "prgd_onboarding_items_contractId_key_key";
ALTER INDEX "Page_alertId_idx" RENAME TO "prgd_pages_alertId_idx";
ALTER INDEX "Page_ticketId_idx" RENAME TO "prgd_pages_ticketId_idx";
ALTER INDEX "Page_userId_ackAt_idx" RENAME TO "prgd_pages_userId_ackAt_idx";
ALTER INDEX "Payment_invoiceId_status_idx" RENAME TO "prgd_payments_invoiceId_status_idx";
ALTER INDEX "Payment_provider_providerRef_idx" RENAME TO "prgd_payments_provider_providerRef_idx";
ALTER INDEX "Payment_teamId_createdAt_idx" RENAME TO "prgd_payments_teamId_createdAt_idx";
ALTER INDEX "PlatformApp_projectId_idx" RENAME TO "prgd_platform_apps_projectId_idx";
ALTER INDEX "PlatformApp_repoFullName_branch_idx" RENAME TO "prgd_platform_apps_repoFullName_branch_idx";
ALTER INDEX "PlatformApp_slug_key" RENAME TO "prgd_platform_apps_slug_key";
ALTER INDEX "Price_resourceType_sku_currency_validFrom_idx" RENAME TO "prgd_prices_resourceType_sku_currency_validFrom_idx";
ALTER INDEX "PrivateIp_networkId_address_key" RENAME TO "prgd_private_ips_networkId_address_key";
ALTER INDEX "PrivateIp_serverId_key" RENAME TO "prgd_private_ips_serverId_key";
ALTER INDEX "PrivateNetwork_projectId_regionId_key" RENAME TO "prgd_private_networks_projectId_regionId_key";
ALTER INDEX "PrivateNetwork_regionId_cidr_key" RENAME TO "prgd_private_networks_regionId_cidr_key";
ALTER INDEX "PrivateNetwork_regionId_poolIndex_key" RENAME TO "prgd_private_networks_regionId_poolIndex_key";
ALTER INDEX "ProductInterest_product_idx" RENAME TO "prgd_product_interests_product_idx";
ALTER INDEX "ProductInterest_teamId_product_key" RENAME TO "prgd_product_interests_teamId_product_key";
ALTER INDEX "Project_teamId_slug_key" RENAME TO "prgd_projects_teamId_slug_key";
ALTER INDEX "PublicIp_address_key" RENAME TO "prgd_public_ips_address_key";
ALTER INDEX "PublicIp_status_regionId_idx" RENAME TO "prgd_public_ips_status_regionId_idx";
ALTER INDEX "Responsibility_contractId_area_key" RENAME TO "prgd_responsibilities_contractId_area_key";
ALTER INDEX "Runbook_slug_key" RENAME TO "prgd_runbooks_slug_key";
ALTER INDEX "Runbook_title_idx" RENAME TO "prgd_runbooks_title_idx";
ALTER INDEX "Server_hostId_idx" RENAME TO "prgd_servers_hostId_idx";
ALTER INDEX "Server_managedBy_idx" RENAME TO "prgd_servers_managedBy_idx";
ALTER INDEX "Server_managedToken_key" RENAME TO "prgd_servers_managedToken_key";
ALTER INDEX "Server_projectId_status_idx" RENAME TO "prgd_servers_projectId_status_idx";
ALTER INDEX "ServerAction_serverId_startedAt_idx" RENAME TO "prgd_server_actions_serverId_startedAt_idx";
ALTER INDEX "ServerAction_workflowId_key" RENAME TO "prgd_server_actions_workflowId_key";
ALTER INDEX "Session_userId_revokedAt_idx" RENAME TO "prgd_sessions_userId_revokedAt_idx";
ALTER INDEX "Snapshot_serverId_kind_idx" RENAME TO "prgd_snapshots_serverId_kind_idx";
ALTER INDEX "SshKey_fingerprint_key" RENAME TO "prgd_ssh_keys_fingerprint_key";
ALTER INDEX "StorageKey_accessKey_key" RENAME TO "prgd_storage_keys_accessKey_key";
ALTER INDEX "StorageKey_projectId_idx" RENAME TO "prgd_storage_keys_projectId_idx";
ALTER INDEX "Team_slug_key" RENAME TO "prgd_teams_slug_key";
ALTER INDEX "Ticket_assigneeId_status_idx" RENAME TO "prgd_tickets_assigneeId_status_idx";
ALTER INDEX "Ticket_contractId_status_idx" RENAME TO "prgd_tickets_contractId_status_idx";
ALTER INDEX "Ticket_status_priority_createdAt_idx" RENAME TO "prgd_tickets_status_priority_createdAt_idx";
ALTER INDEX "Ticket_teamId_status_idx" RENAME TO "prgd_tickets_teamId_status_idx";
ALTER INDEX "TicketMessage_ticketId_createdAt_idx" RENAME TO "prgd_ticket_messages_ticketId_createdAt_idx";
ALTER INDEX "UsageEvent_projectId_at_idx" RENAME TO "prgd_usage_events_projectId_at_idx";
ALTER INDEX "UsageEvent_resourceType_resourceId_at_key" RENAME TO "prgd_usage_events_resourceType_resourceId_at_key";
ALTER INDEX "UsageRecord_invoiceId_idx" RENAME TO "prgd_usage_records_invoiceId_idx";
ALTER INDEX "UsageRecord_projectId_hourStart_idx" RENAME TO "prgd_usage_records_projectId_hourStart_idx";
ALTER INDEX "UsageRecord_resourceType_resourceId_hourStart_key" RENAME TO "prgd_usage_records_resourceType_resourceId_hourStart_key";
ALTER INDEX "User_email_key" RENAME TO "prgd_users_email_key";
ALTER INDEX "Volume_projectId_idx" RENAME TO "prgd_volumes_projectId_idx";
ALTER INDEX "Volume_serverId_idx" RENAME TO "prgd_volumes_serverId_idx";
ALTER INDEX "WebhookDelivery_deliveredAt_nextAttemptAt_idx" RENAME TO "prgd_webhook_deliveries_deliveredAt_nextAttemptAt_idx";
ALTER INDEX "WorkLog_contractId_billedPeriod_idx" RENAME TO "prgd_work_logs_contractId_billedPeriod_idx";
ALTER INDEX "WorkLog_contractId_workedAt_idx" RENAME TO "prgd_work_logs_contractId_workedAt_idx";
